-- Generated by nwg-displays on 2026-09-13 at 18:00:20. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2160x1440@60.0",
    position = "0x0",
    scale = 1.2000000000000002,
    vrr = 0
})
