# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DBDDDF
background         #162330
cursor             #3D474F

active_tab_foreground     #162330
active_tab_background     #DBDDDF
inactive_tab_foreground   #DBDDDF
inactive_tab_background   #162330

active_border_color   #DBDDDF
inactive_border_color #162330
bell_border_color     #899AA6

color0      #ADAFB3
color1		#899AA6
color2		#8293A0
color3		#445868
color4		#2B373F
color5		#1E252B
color6		#131A21
color7		#525C64
color8		#808F9B
color9		#B6CDDE
color10		#ADC4D5
color11		#5B768B
color12		#3A4A55
color13		#28313A
color14		#1A232C
color15		#D2DDE6
